#!/usr/bin/env python3
"""Minimal console for monitoring brymen bm257s multimeter data"""
# pylint: disable=invalid-name

import bm257s


def main():
    """Start minimal bm257s console
    """
    with bm257s.BM257sSerialInterface() as mm:
        while 1:
            print(mm.read())


if __name__ == "__main__":
    main()
