#!/usr/bin/env python3
"""Minimal console for monitoring brymen bm257s multimeter data"""
# pylint: disable=invalid-name

import bm257s


def main():
    """Start minimal bm257s console
    """
    with bm257s.BM257sSerialInterface() as mm:
        while 1:
            try:
                measurement = mm.read()
                print(f"{measurement[0]}: {measurement[1]}")

            except RuntimeError as ex:
                print(f"Could not read current measurement: {ex}")


if __name__ == "__main__":
    main()
